version: '3.9'
services:
  plantz:
    image: 2k12/plantz
    container_name: backend
    ports:
      - 4000:4000
    command: npm run dev
  plantzfront:
    image: 2k12/plantzfront
    container_name: front
    ports:
      - 8080:8080
    command: npm run dev
    